CFLAGS += -DWITH_UIP=1 -I
PROJECT_SOURCEFILES += ../knot_protocol.c ../knot_network.c ../knot_uip_network.c ../channeltable.c ../knot_channel_state_uip.c knot-sensor.c light.c
CONTIKI_PROJECT = app-sensor
all: $(CONTIKI_PROJECT)
CONTIKI =/home/user/contiki
include $(CONTIKI)/Makefile.include
