CFLAGS += -DWITH_UIP=1 -I
PROJECT_SOURCEFILES += ../knot-network.c ../channeltable.c
CONTIKI_PROJECT = knot-sensor
all: $(CONTIKI_PROJECT)
CONTIKI =/home/user/contiki
include $(CONTIKI)/Makefile.include
