CFLAGS += -DWITH_UIP=1 -I
PROJECT_SOURCEFILES+= ../knot-network.c ../channeltable.c ../knot_channel_state_uip.c knot-controller.c 
CONTIKI_PROJECT = controller_application_1
all: $(CONTIKI_PROJECT)
CONTIKI =/home/user/contiki
include $(CONTIKI)/Makefile.include